data_source:
  name: shopify_product_variant
  owners:  # This will throw an error unless you add a list of owners or remove this entry.
  sql_table: SHOPIFY.PRODUCT_VARIANT ### Update to your product_variant schema.table
  identifiers:
    - name: product
      type: primary
      expr: product_id
    - name: inventory_item
      type: foreign
      expr: inventory_item_id
  dimensions:
    - name: ds
      type: time
      type_params:
        is_primary: True
        time_granularity: day
      expr: created_at::date # Casting to date using Snowflake syntax. Update as needed based on your warehouse.
  measures:
    - name: average_product_price
      agg: average
      expr: price
      create_metric: true
    - name: total_inventory_product_quantity
      agg: sum
      expr: inventory_quantity
      create_metric: true
    - name: total_inventory_value
      agg: sum
      expr: inventory_quantity * price
      create_metric: true 
